# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApitoCli < Formula
  desc "Apito CLI"
  homepage "https://apito.io"
  version "0.3.7"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/apito-io/cli/releases/download/v0.3.7/apito_0.3.7_darwin_amd64.tar.gz"
      sha256 "a3106c420e0d94ca322c41150d3d32fe6e5c7d311cefbec527385eb64189c458"

      def install
        bin.install "apito"
      end
    end
    on_arm do
      url "https://github.com/apito-io/cli/releases/download/v0.3.7/apito_0.3.7_darwin_arm64.tar.gz"
      sha256 "2fb3e3b1cde7d4f92e4e7a42d8c38aed74b0a81fa0f94bb983b4f96cd060d77a"

      def install
        bin.install "apito"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apito-io/cli/releases/download/v0.3.7/apito_0.3.7_linux_amd64.tar.gz"
        sha256 "1d068ec8dd69bb35ddcaa1f778ecd66fa3f0740c458bc04c59c828223fc41ca8"

        def install
          bin.install "apito"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apito-io/cli/releases/download/v0.3.7/apito_0.3.7_linux_arm64.tar.gz"
        sha256 "cac78b37e9d3280870fb18747de9e0e3651cc7aa1b6e3a9f3d0572d8a66d46b0"

        def install
          bin.install "apito"
        end
      end
    end
  end

  test do
    system "#{bin}/apito", "--version"
  end
end
