# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApitoCli < Formula
  desc "Apito CLI"
  homepage "https://apito.io"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/apito-io/cli/releases/download/v0.3.0/apito_0.3.0_darwin_amd64.tar.gz"
      sha256 "e004b799c9b2be1342307de64e60ab2a0917069f33266042a9114ad63c7775ba"

      def install
        bin.install "apito"
      end
    end
    on_arm do
      url "https://github.com/apito-io/cli/releases/download/v0.3.0/apito_0.3.0_darwin_arm64.tar.gz"
      sha256 "8834731e6b334818dfab2e55ffe5a22c49e4ec68343a93113855392b5b3ac12c"

      def install
        bin.install "apito"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apito-io/cli/releases/download/v0.3.0/apito_0.3.0_linux_amd64.tar.gz"
        sha256 "498d19094e5886668b425ac0f51298dbf9b20e8295a49fffc18f28f7401f1fd4"

        def install
          bin.install "apito"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apito-io/cli/releases/download/v0.3.0/apito_0.3.0_linux_arm64.tar.gz"
        sha256 "ea23a9e2d699d9186cf7c998e6bf8fcc81790257b42a669899f2672f75eae4b7"

        def install
          bin.install "apito"
        end
      end
    end
  end

  test do
    system "#{bin}/apito", "--version"
  end
end
